"""initial migration

Revision ID: b02fa11726d7
Revises: 
Create Date: 2025-03-25 12:53:55.645213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b02fa11726d7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assistants', 'department',
               existing_type=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.create_index(op.f('ix_assistants_id'), 'assistants', ['id'], unique=False)
    op.drop_constraint('FK_assistants_user_id', 'assistants', type_='foreignkey')
    op.create_foreign_key(None, 'assistants', 'users', ['user_id'], ['id'])
    op.alter_column('doctors', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_doctors_id'), 'doctors', ['id'], unique=False)
    op.drop_constraint('FK_doctors_user_id', 'doctors', type_='foreignkey')
    op.create_foreign_key(None, 'doctors', 'users', ['user_id'], ['id'])
    op.alter_column('patient_assignments', 'assistant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_patient_assignments_id'), 'patient_assignments', ['id'], unique=False)
    op.drop_constraint('FK_patient_assignments_assistant', 'patient_assignments', type_='foreignkey')
    op.create_foreign_key(None, 'patient_assignments', 'assistants', ['assistant_id'], ['id'])
    op.alter_column('patients', 'address',
               existing_type=sa.TEXT(length=2147483647, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('patients', 'doctor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.drop_constraint('FK__patients__doctor__1CF15040', 'patients', type_='foreignkey')
    op.create_foreign_key(None, 'patients', 'doctors', ['doctor_id'], ['id'])
    op.alter_column('treatment_applications', 'treatment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_treatment_applications_id'), 'treatment_applications', ['id'], unique=False)
    op.alter_column('treatments', 'description',
               existing_type=sa.TEXT(length=2147483647, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('treatments', 'doctor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_treatments_id'), 'treatments', ['id'], unique=False)
    op.drop_constraint('FK_treatments_doctor_id', 'treatments', type_='foreignkey')
    op.create_foreign_key(None, 'treatments', 'doctors', ['doctor_id'], ['id'])
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_constraint(None, 'treatments', type_='foreignkey')
    op.create_foreign_key('FK_treatments_doctor_id', 'treatments', 'doctors', ['doctor_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_treatments_id'), table_name='treatments')
    op.alter_column('treatments', 'doctor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('treatments', 'description',
               existing_type=sa.Text(),
               type_=sa.TEXT(length=2147483647, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    op.drop_index(op.f('ix_treatment_applications_id'), table_name='treatment_applications')
    op.alter_column('treatment_applications', 'treatment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.create_foreign_key('FK__patients__doctor__1CF15040', 'patients', 'doctors', ['doctor_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.alter_column('patients', 'doctor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('patients', 'address',
               existing_type=sa.String(),
               type_=sa.TEXT(length=2147483647, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    op.drop_constraint(None, 'patient_assignments', type_='foreignkey')
    op.create_foreign_key('FK_patient_assignments_assistant', 'patient_assignments', 'assistants', ['assistant_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_patient_assignments_id'), table_name='patient_assignments')
    op.alter_column('patient_assignments', 'assistant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'doctors', type_='foreignkey')
    op.create_foreign_key('FK_doctors_user_id', 'doctors', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_doctors_id'), table_name='doctors')
    op.alter_column('doctors', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'assistants', type_='foreignkey')
    op.create_foreign_key('FK_assistants_user_id', 'assistants', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_assistants_id'), table_name='assistants')
    op.alter_column('assistants', 'department',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    # ### end Alembic commands ###
